services:
  app:
    build: .
    container_name: fleet-sustainability-app
    ports:
      - "8081:8080"
    command: ["./fleet-backend"]
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017
      - MONGO_DB=fleet
      - MQTT_BROKER_URL=tcp://mosquitto:1883
      - MQTT_TELEMETRY_TOPIC=fleet/telemetry
  
  mongo:
    image: mongo:6.0
    container_name: fleet-sustainability-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: fleet-sustainability-mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: fleet-sustainability-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./configs/mosquitto:/mosquitto/config